### ISSUE TITLE
开销有多大??

### ISSUE THREAD

**Issue by 55cc** [qq918482974/WinWallpaper#1]

**Comment by ghost** [comment]
（我不是原作者，但我经允许后修改了他的代码）
据我观察，在我的i7-6700HQ上，CPU使用不超过5%
![default](https://user-images.githubusercontent.com/18734999/39078340-a9662ec0-453b-11e8-83d7-1bfe17463c9a.png)
内存使用emmmm取决于你的视频大小。
因为使用的是WPF的MediaPlayer，控件内存是系统托管的。
（当然了你要是播放4K甚至8K视频，CPU和内存占用率肯定会增加。）

**Comment by 55cc** [comment]
还在用i3的老电脑路过...
